### ISSUE TITLE
fix: 리뷰 조회 슬로우 쿼리 개선

### ISSUE THREAD

**Issue by gmelon** [strangebros/nork-backend#77]
### 예외 개요
- review 조회 쿼리 성능 개선
- 현재 리뷰 조회 단건 쿼리 실행에 1.5초 가량 소요
    - 마이페이지 로딩 지연의 원인으로 작용한 것으로 보임

### 예외 원인
- 중첩 쿼리 및 서브 쿼리?

### 작업 내용
- 원인 분석 후 쿼리 성능 개선

### Todo list
-

**Comment by sootudio** [comment]
![image](https://github.com/user-attachments/assets/ec0f4304-1c6a-4615-8e4a-33df64d3fab5)
해당 쿼리로 조회해 봤을 때, 처음에는 15s 가량이 나왔습니다.

![image](https://github.com/user-attachments/assets/59f750cf-d0d1-4639-b44e-661659a3b137)
지금은 18s 정도가 나왔습니다.
